config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'welcome/index'
  get 'articles/alert'
  resources :users do 
    get 'login', on: :collection
    get 'logout', on: :collection
    post 'auth_user', on: :collection
  end
  resources :images
  resources :categories
  resources :likes
  resources :articles do
  	resources :comments
  end
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord  
  belongs_to :article
  belongs_to :user
  has_many :likes, as: :like, dependent: :destroy

  after_save :send_mail

  private

  def send_mail
    UserMailer.comment_notification_email(self).deliver_later
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  skip_before_action :verify_authenticity_token
  include CommentsHelper
  
  def index
    
  end
	
  def create
    @article = Article.find(params[:article_id])
    if params[:article_id].present? && params[:body].present?
      @comment = @article.comments.build({body: params[:body],user_id: current_user.id})
      if @comment.save
        flash[:success] = "Comment saved"
        @comment
      else
        flash[:danger] = "Comment not saved"
        redirect_to article_path(@article)
      end
    else
      flash[:danger] = "Comment not saved"
      redirect_to article_path(@article)
    end
  end
  
  def destroy
    if params[:article_id].present? && params[:id].present?
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      if @comment.destroy
        flash[:danger] = "Comment deleted"
      else
        flash[:danger] = "Comment cannot deleted"
        redirect_to article_path(@article)
      end
    else
      flash[:danger] = "Comment cannot deleted"
      redirect_to article_path(@article)
    end
  end
	
  private

  def comment_params
    params.require(:comment).permit(:body)
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-xs-5 col-xs-offset-5">
    <h4 style="font-weight: bold">Comments</h4>
  </div>
  
  <div class="col-xs-12">
    <% @article.comments.each do |comment| %>
      <div class="col-xs-12" id="cm">
        
        <%= link_to user_path(comment.user.id), id: "profile_link" do%>
          <%= image_tag( get_user_image(comment.user), width: "32", height: "32", id: "commenter_img", alt: comment.user.username) %>
        <% end %>            
        
        <% if current_user.id == comment.user_id %>  
          <div class="col-xs-12">
            <%= link_to 'Destroy Comment', 'javascript:void(0)', article: @article.id, comment: comment.id, class: 'link', data: { confirm: 'Are you sure?'} %>
          </div>
        <% end %>
        <%= comment.body %>

        <% entity_like_status = enitity_liked('Comment', comment.id) %>
        <% link_class = entity_like_status ? "img_linkd" : "img_link" %>
        <% ids_of_like = comment.likes.where(user_id: current_user).ids %>
        <% likeId = entity_like_status ?  ids_of_like : '' %>
        
        <span class="form_like<%=comment.id%>">
          <%= render 'likes/likeLink',likeId: likeId, link_class: link_class, likeable_type: "Comment", likeable_id: comment.id %>
          </span>
        <span class="like_count<%=comment.id%>">
          <%= count_likes(comment.id, 'Comment') %>
        </span>
        
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_with url: article_comments_path(@article.id), :html => {class: "form-horizontal comment-form", role: "from"} do |form| %>
      <div class="form-group">
        <%= form.text_field :body, rows: 6, class: "form-control", id: "text", placeholder: "Enter Comment..." %>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit class: "btn b tn-primary", id: "butt"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$("#com").html("<%= escape_javascript(render(:partial => @comment)) %>");
$("#text").val("");
$("#text").attr("placeholder", "Enter Comment...");

app/views/comments/destroy.js.erb
$("#com").html("<%= escape_javascript(render(:partial => @comment)) %>");
$("#text").val("");
$("#text").attr("placeholder", "Enter Comment...");