config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'welcome/index'
  get 'articles/alert'
  resources :users do 
    get 'login', on: :collection
    get 'logout', on: :collection
    post 'auth_user', on: :collection
  end
  resources :images
  resources :categories
  resources :likes
  resources :articles do
  	resources :comments
  end
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true
	has_many :comments, dependent: :destroy
	has_many :likes, as: :like, dependent: :destroy
	belongs_to :user
	belongs_to :category
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  include ArticlesHelper

  def new
    @user = User.new
		@article = Article.new
	end

	def edit
  end

  def create
    @article = current_user.articles.create(article_params)
 	  if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to @article
  	else
      flash[:success] = "Article was not created"
      render 'new'
  	end
	end

	def update
	  if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to @article
    else
      flash[:failure] = "Can't update article"
      render 'edit'
    end
	end

  def show
	end
  	
  def index
    @article = Article.all
  end
  
  def destroy
    if @article.destroy
      flash[:danger] = "Article was successfully deleted"
    else
      flash[:danger] = "Can't delete article"
    end
    redirect_to articles_path
	end
  
  private
  
  def set_article
    @article = Article.find_by_id(params[:id])
    if @article.blank?
      false
    end
  end
  def article_params
    params.require(:article).permit(:title, :text, :category_id)
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def check_whether_user_created_article(article_id)
		current_user.articles.ids.include?article_id
	end

	def get_category_name(article_instance)
		article_instance.category.name
	end

	def count_likes(like_id,like_type)
		like_type.constantize.find(like_id).likes.size
	end  
end

app/views/articles/_error.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offsset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li style="color: red; list-style-type: none;"><%= msg %>*</li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'error', obj: @article%>
<div class="row">
  <div class="col-xs-12">
    <%= form_with model: @article, local: true, :html => {class: "form-horizontal", role:"from"} do |form| %>
      <div class="form-group">
        <%= form.label :title, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= form.text_field :title, class: "form-control", placeholder: "Enter Title..." %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :Category, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= form.collection_select(:category_id, Category.all, :id, :name)%>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :text, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= form.text_area :text, rows: 8, class: "form-control", placeholder: "Enter Title..." %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit class: "btn btn-primary"%>
        </div>
      </div>
    <% end %>
    
    <div class="col-xs-4 col-xs-offset-4">
      <%= link_to 'Back', articles_path%>
    </div>
    
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
	<%= render 'form' %>
 

app/views/articles/index.html.erb
<h1 align="center">Listing articles</h1>
  <% @article.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>    
          </div>
          
          <div class="article-body">
            <%= article.text %>     
          </div>
          
          <div class="article-actions">
            <% if check_whether_user_created_article(article.id) %>
              <%= link_to "Edit", edit_article_path(@article.ids), class: "btn btn-xs btn-primary" %>    
              <%= link_to "Delete", article_path(article), method: :delete,data: { confirm: "Are you sure you want to delete the article?"},class: "btn btn-xs btn-danger"
              %>
            <% end %>
          </div>
          
        </div>
      </div>
    </div>
  <% end %>
<%= link_to 'Add Title', articles_new_path %>

app/views/articles/new.html.erb
<h1 style="text-align: center; font-weight: bold">New article</h1>
	<%= render 'form' %> 

app/views/articles/show.html.erb
<h2 align="center">Title : <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  
  <h3 style="font-style: italic; text-transform: capitalize;"><%= @article.text%></h3>
  
  <div class="article-actions">
    
    <div id="com" style="padding-left: 15px;">
      <%= render 'comments/comment' %>
    </div>
    
    <%= render 'comments/form' %>
    
    <% if check_whether_user_created_article(@article.id) %>
      <%= link_to "Edit", edit_article_path(@article), class: "btn btn-sm btn-primary" %>
      <%= link_to "Delete", article_path(@article), method: :delete,data: { confirm: "Are you sure you want to delete the article?"},class: "btn btn-sm btn-danger" %>
    <% end %>
  
  </div>
  <h5><i><b>Category : </b><%= get_category_name(@article) %></i></h5>

    <span class="form_like">
      <% entity_like_status = enitity_liked('Article', @article.id) %>
      <% link_class = entity_like_status ? "img_linkd" : "img_link" %>
      <% ids_of_like = @article.likes.ids %>
      <% likeId = entity_like_status ?  ids_of_like : '' %>
      <%= render 'likes/likeLink',likeId: likeId, link_class: link_class, likeable_type: "Article", likeable_id: @article.id%></span>
    <span class="like_count">
      <%= count_likes(@article.id, 'Article') %>
    </span>  
</div> 