config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'welcome/index'
  get 'articles/alert'
  resources :users do 
    get 'login', on: :collection
    get 'logout', on: :collection
    post 'auth_user', on: :collection
  end
  resources :images
  resources :categories
  resources :likes
  resources :articles do
  	resources :comments
  end
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

	validates :email, presence: true
	validates :password, presence: true
	validates :username, presence: true
	has_many :comments, dependent: :destroy
	has_many :articles, dependent: :destroy
	has_many :likes, as: :like, dependent: :destroy
  has_one :image, dependent: :destroy

  accepts_nested_attributes_for :image 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user_by_id, only: [:edit, :update, :show, :destroy]

  def new
    @user = User.new
  end

  def edit
  end
  
  def create
    if user_params.present?
      @user = User.new({:username => user_params[:username], :email => user_params[:email], :password => user_params[:password]})
      if @user.save
        if user_params[:user_image_attributes].present?
          image_params = {picture: user_params[:user_image_attributes][:picture]}
          image = @user.build_image(image_params)
          if image.save
            flash[:success] = "User Profile was successfully created"
            redirect_to login_users_path
          else
            flash[:danger] = "Can't create users account"      
            render 'new'
          end
        else
          image = @user.build_image
          if image.save
            flash[:success] = "User Profile was successfully created"
            redirect_to login_users_path
          else
            flash[:danger] = "Can't create users account"      
            render 'new'
          end
        end
      else
        flash[:danger] = "Can't create users account"      
        render 'new'
      end
    else
      flash[:danger] = "Can't create users account"      
      render 'new'
    end
  end

  def update
    if user_params.present?
      if @user.update({:username => user_params[:username], :email => user_params[:email], :password => user_params[:password]})
        if user_params[:user_image_attributes].present?
          image_params = {picture: user_params[:user_image_attributes][:picture]}
          if @user.image != nil
            if @user.image.update(image_params)
              flash[:success] = "User Profile was successfully updated"
              redirect_to user_path(@user.id)
            else
              flash[:danger] = "User Profile not updated"
              render 'edit'
            end
          else
            image = @user.build_image(image_params)
            if image.save
              flash[:success] = "User Profile was successfully updated"
              redirect_to user_path(@user.id)
            else
              flash[:danger] = "User Profile not updated"
              render 'edit'
            end
          end
        else
          flash[:success] = "User Profile was successfully updated"
          redirect_to user_path(@user.id)
        end
      else
        flash[:danger] = "User Profile not updated"
        render 'edit'
      end
    else
      flash[:danger] = "User Profile not updated"
      render 'edit'
    end
  end
  
  def show
  end

  def index
    @users = User.all
  end

  def destroy
    if @user.destroy
      flash[:danger] = "User Profile was successfully deleted"
    else
      flash[:danger] = "Can;t delete user profile"
    end
    redirect_to users_path
  end

  def login
    if current_user!=nil
      redirect_to articles_path  
    else
      render 'login'
    end
  end

  def auth_user
    @user = User.find_by_email(params[:email])
    if(@user!=nil && @user.password==params[:password]) 
      flash[:success] = "User Successfully Login"
      session[:user_id] = @user.id
      redirect_to articles_path
    else
      flash[:danger] = "Invalid Userid or Password"
      redirect_to login_users_path
    end
  end

  def logout
    current_user = session[:user_id] = nil  
    redirect_to welcome_index_path
  end

  private

  def find_user_by_id
    @user = User.find(params[:id])
    if @user.blank?
      false
    end
  end
  
  def user_params
    params.require(:user).permit(:username, :email, :password, user_image_attributes: [:picture])
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_with model: @user, multipart: true, local: true, :html => {class: "form-horizontal", role:"from"} do |form| %>
    
    <div class="form-group">
      <%= form.label :username, class: "col-sm-2 control-label"  %>
      <div class="col-sm-10">
        <%= form.text_field :username , class: "form-control", id: "name"%><span id="sname"></span>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :email, class: "col-sm-2 control-label"%>
      <div class="col-sm-10">
        <%= form.text_field :email, class: "form-control", id: "email"%><span id="semail"></span>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :password, class: "col-sm-2 control-label"  %>
      <div class="col-sm-10">
        <%= form.password_field :password, class: "form-control" , id: "password"%><span id="spassword"></span>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :Confirm_Password, class: "col-sm-2 control-label"  %>
      <div class="col-sm-10">
        <%= form.password_field :cpassword, class: "form-control", id: "cpassword"%><span></span>
      </div>
    </div>

    <%= form.fields_for :user_image_attributes do |ff| %>

    <div class="form-group">
      <%= ff.label :Profile_Image, class: "col-sm-2 control-label"  %>
      <div class="col-sm-10">
        <%= ff.file_field :picture, accept: 'image/jpeg, image/gif, image/png', class: "form-control" , id: "picture"%><span id="spicture"></span>
      </div>
    </div>

    <% end %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit class: "btn btn-primary", id: "btn"%>
      </div>
    </div>
    <% end %> 
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'form', user: @user %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table id="users">
  <thead>
    <tr>
      <th>Id </th>
      <th>Username </th>
      <th>Email </th>
      <th>password </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-xs-12">
      <h1><center>LOGIN</center></h1>
        <%= form_with url: auth_user_users_path, :html => {class: "form-horizontal", role:"from"} do |form| %>
      <div class="form-group">
        <%= form.label :Email, class: "col-sm-2 control-label"%>
        <div class="col-sm-10">
          <%= form.text_field :email , class: "form-control", id: "email"%><span id="semail"></span>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :Password, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= form.password_field :password, class: "form-control", id: "password"%><span id="spassword"></span>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit :LOGIN, class: "btn btn-primary", id: "btn"%>
        </div>
      </div>
      <% end %> 
    </div>
  </div>
  <%= link_to 'Back', root_path %>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
	<h1 style="text-align: center; font-weight: bold">New User</h1>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="fix_block">
    <div id="lft">
      <p>
        <strong>Username:</strong>
        <%= @user.username %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <p>
        <strong>Articles:</strong>
        <%= @user.articles.count %>
      </p>
      <% if @user == current_user %>
        <%= link_to 'Edit', edit_user_path(@user) %> |
      <% end %>
    </div>
    <div id="rgt">
      <%= image_tag( get_user_image(@user), width: "120", height: "120", id: "img", alt: @user.username) %>
      
    </div>
  </div>
</div>