config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'welcome/index'
  get 'articles/alert'
  resources :users do 
    get 'login', on: :collection
    get 'logout', on: :collection
    post 'auth_user', on: :collection
  end
  resources :images
  resources :categories
  resources :likes
  resources :articles do
  	resources :comments
  end
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
		<small>
			Copyright &copy<a href="#"></a>
		</small>
		<nav>
			<ul>
				<li><%= link_to 'About us', '#', id:"footer"%></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row flash">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg| %>
    <div class='alert alert-<%="#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">&#215</a>
			<%= content_tag :div, msg , :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>	
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" id="navv">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <% if current_user==nil %>
      <%= link_to 'blog', root_path, class: "navbar-collapse-brand", id: "blog" %>
      <% else %>
      <%= link_to 'blog', articles_path, class: "navbar-collapse-brand", id: "blog" %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" id="search" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="navbar-nav navbar-right">
        <li style="list-style-type: none;">
          <%if current_user!=nil %>
            <br>
            <%= link_to user_path(current_user.id), id: "p" do%>
              <%= image_tag( get_user_image(current_user), width: "64", height: "64", id: "img", alt: current_user.username) %>
            <% end %>            
            <%= link_to "LOGOUT", logout_users_path, class: "navbar-collapse-brand", id: "logout" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>